// client/src/pages/User/Register.jsx
import { Button, Checkbox, Divider, Form, Input } from 'antd';
import CryptoJS from 'crypto-js';
import { connect } from 'dva';
import { Link } from 'umi';
import style from './style.less';
const Register = (props) => {
  const isMobile = window.document.body.clientWidth <= 575;
  const [regForm] = Form.useForm();
  const onFinish = async (value) => {
    props.register({
      uname: window.encodeURIComponent(value.uname),
      userName: value.userName,
      upwd: CryptoJS.MD5(value.upwd).toString(),
      email: value.email,
      isInit: value.isInit ? 1 : 0,
    });
  };

  const onFinishFailed = (errorInfo) => {
    console.log('Failed:', errorInfo);
  };
  // const sendCode = ()=>{
  //   if(!(regForm.getFieldValue('email')&&regForm.getFieldValue('uname'))){
  //     message.err('请先输入Email和登录名')
  //     return false
  //   }
  //   props.sendCode({
  //     email:regForm.getFieldValue('email').trim(),
  //     uname:regForm.getFieldValue('uname').trim()
  //   })
  // }
  return (
    <div className={style.login}>
      <h1 className={style.title}>注 册</h1>
      <Form
        name="login"
        form={regForm}
        labelCol={{ span: 4 }}
        wrapperCol={{ span: 16 }}
        initialValues={{ isInit: true }}
        onFinish={onFinish}
        onFinishFailed={onFinishFailed}
        autoComplete="off"
      >
        <Form.Item
          label="登录名"
          name="uname"
          hasFeedback
          validateTrigger="onBlur"
          rules={[
            {
              required: true,
              message: '请输入登录名',
            },
            {
              validator: async (rule, val, callback) => {
                if (val !== undefined && val !== '') {
                  let res = await props.checkUname({ uname: window.encodeURIComponent(val.trim()) });
                  if (res && res.code === 200) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error(res.msg));
                }
              },
            },
          ]}
        >
          <Input placeholder="请输入登录名" size="large" />
        </Form.Item>
        <Form.Item
          label="昵称"
          name="userName"
          hasFeedback
          validateTrigger="onBlur"
          rules={[
            {
              required: true,
              message: '请输入昵称',
            },
          ]}
        >
          <Input placeholder="请输入昵称" size="large" />
        </Form.Item>
        <Form.Item
          label="邮箱"
          name="email"
          hasFeedback
          validateTrigger="onBlur"
          rules={[
            {
              required: true,
              message: '请输入电子邮箱',
            },
            {
              validator: async (rule, val, callback) => {
                if (val !== undefined && val !== '') {
                  let res = await props.checkUserEmail({ email: val.trim() });
                  if (res && res.code === 200) {
                    return Promise.resolve();
                  }
                  return Promise.reject(new Error(res.msg));
                }
              },
            },
          ]}
        >
          <Input placeholder="请输电子邮箱" size="large" />
        </Form.Item>
        {/* <Form.Item label="验证码" style={{ marginBottom: 0 }}>
        <Form.Item name="code"
          wrapperCol={{
            offset: 0,
            span: 16,
          }}
          hasFeedback
          rules={[
            {
              required: true,
              message: '请输入验证码',
            },
            {
              validator: (rule, val, callback) => {
                console.log('val: ', val);
                if (val !== undefined && val !== "") {
                  if (!new RegExp(/^[\da-zA-Z]{4}$/).test(val)) {
                    return Promise.reject(new Error("请输入4位有效验证码"));
                  } else {
                    return Promise.resolve();
                  }
                } else {
                  return Promise.resolve();
                }
              },
            }
          ]}
        >
          <Input placeholder="请输入4位验证码" onClick={sendCode} size="large" />
        </Form.Item>
        <Button type='primary' className={style.sendCode}>发送验证码</Button>
      </Form.Item> */}
        <Form.Item
          label="密码"
          name="preupwd"
          hasFeedback
          rules={[
            {
              required: true,
              message: '请输入密码',
            },
            {
              validator: (rule, val, callback) => {
                if (val !== undefined && val !== '') {
                  if (!new RegExp(/^[\da-zA-Z]{6,}$/).test(val)) {
                    return Promise.reject(new Error('请输入6位以上由数字、字母组合密码'));
                  } else {
                    return Promise.resolve();
                  }
                } else {
                  return Promise.resolve();
                }
              },
            },
          ]}
        >
          <Input.Password placeholder="请输入6位以上由数字、字母组合密码" size="large" />
        </Form.Item>
        <Form.Item
          label="确认密码"
          name="upwd"
          hasFeedback
          rules={[
            {
              required: true,
              message: '请确认密码',
            },
            {
              validator: (rule, val, callback) => {
                if (val !== undefined && val !== '') {
                  let preupwd = regForm.getFieldValue('preupwd') || '';
                  if (val !== preupwd) return Promise.reject(new Error('两次输入的密码不一致'));
                  return Promise.resolve();
                } else {
                  return Promise.resolve();
                }
              },
            },
          ]}
        >
          <Input.Password placeholder="请确认密码" size="large" />
        </Form.Item>
        <Form.Item
          wrapperCol={{
            offset: isMobile ? 0 : 4,
            span: 16,
          }}
          name="isInit"
          valuePropName="checked"
        >
          <Checkbox>是否默认公共网址</Checkbox>
        </Form.Item>
        <Form.Item
          wrapperCol={{
            offset: isMobile ? 0 : 4,
            span: 16,
          }}
        >
          <Button type="primary" htmlType="submit" block size="large">
            注册
          </Button>
          <p style={{ margin: '1rem auto', color: '#fff' }}>
            已有账号?直接
            <Link to="/user/login"> 登 录</Link>
          </p>
        </Form.Item>
      </Form>
    </div>
  );
};

const mapStateToProps = (state) => ({
  userInfo: state.User.userInfo,
  isLight: state.global.isLight,
});

const mapDispatchToProps = (dispatch) => ({
  checkUserEmail(params) {
    return dispatch({
      type: 'User/checkUserEmail',
      payload: params,
    });
  },
  checkUname(params) {
    return dispatch({
      type: 'User/checkUname',
      payload: params,
    });
  },
  sendCode(params) {
    return dispatch({
      type: 'User/sendCode',
      payload: params,
    });
  },
  register(params) {
    return dispatch({
      type: 'User/register',
      payload: params,
    });
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(Register);

// pages/register.vue
<template>
  <section class="account">
    <div class="login-title">注册</div>
    <el-form
      ref="account"
      :model="account"
      :rules="rules"
      label-width="4rem"
    >
      <el-form-item
        label="昵称"
        prop="uname"
      >
        <el-input
          v-model="account.uname"
          placeholder="请输入用户名"
        />
      </el-form-item>
      <el-form-item
        label="邮箱"
        prop="email"
      >
        <el-input
          v-model="account.email"
          placeholder="请输入电子邮箱"
        />
        <el-button
          size="mini"
          round
          type="success"
          @click="sendMsg"
        >发送验证码</el-button>
        <span class="status">{{ statusMsg }}</span>
      </el-form-item>
      <el-form-item
        label="验证码"
        prop="code"
      >
        <el-input
          v-model="account.code"
          maxlength="4"
          placeholder="请输入4位验证码"
        />
      </el-form-item>
      <el-form-item
        label="密码"
        prop="upwd"
      >
        <el-input
          v-model="account.upwd"
          type="password"
          placeholder="请输入6位以上由数字、字母组合"
        />
      </el-form-item>
      <el-form-item
        label="确认密码"
        prop="cpwd"
      >
        <el-input
          v-model="account.cpwd"
          type="password"
          placeholder="请确认密码"
        />
      </el-form-item>
      <el-form-item>
        <el-button
          type="primary"
          @click="register"
        >立即创建</el-button>
        <el-button @click="resetForm('account')">重置</el-button>
      </el-form-item>
      <el-form-item>
        <span class="text">已有账号?</span>
        <el-button type="text">
          <nuxt-link to="/login">立即登录</nuxt-link>
        </el-button>
        <el-button type="text">
          <nuxt-link to="/">回到首页</nuxt-link>
        </el-button>
      </el-form-item>
    </el-form>
  </section>
</template>
<script>
import CryptoJS from "crypto-js";
export default {
  name: "Register",
  layout: "blank",
  data() {
    return {
      statusMsg: "",
      account: {
        uname: "",
        code: "",
        upwd: "",
        cpwd: "",
        email: ""
      },
      rules: {
        uname: [
          {
            required: true,
            type: "string",
            message: "请输入用户名",
            trigger: "blur"
          },
          {
            validator: async(rule, val, callback) => {
              if (val === "") {
                callback(new Error("请输入用户名"));
              } else{
                var {status,data} = await this.$axios.post("/user/check",{uname:val})
                if(status==200 && data.code=='-1'){
                  callback(new Error(data.msg));
                }else{
                  callback();
                }
              }
            },
            trigger: "blur"
          }
        ],
        email: [
          {
            required: true,
            type: "email",
            message: "请输入邮箱",
            trigger: "blur"
          },
          {
            validator: async(rule, val, callback) => {
              if (val === "") {
                callback(new Error("请输电子邮箱"));
              } else{
                console.log('jin')
                var {status,data} = await this.$axios.post("/user/check",{email:val})
                if(status==200 && data.code=='-1'){
                  callback(new Error(data.msg));
                }else{
                  callback();
                }
              }
            },
            trigger: "blur"
          }
        ],
        code: [
          {
            required: true,
            type: "string",
            message: "请输入有效验证码",
            trigger: "blur"
          },
          {
            validator: (rule, val, callback) => {
              if (val === "") {
                callback(new Error("请输入有效验证码"));
              } else if (!new RegExp(/^[\da-zA-Z]{4}$/).test(val)) {
                callback(new Error("请输入4位有效验证码"));
              } else {
                callback();
              }
            },
            trigger: "blur"
          }
        ],
        upwd: [
          {
            required: true,
            message: "请输入密码",
            trigger: "blur"
          },
          {
            validator: (rule, val, callback) => {
              if (val === "") {
                callback(new Error("请输入密码"));
              } else if (!new RegExp(/^[\da-zA-Z]{6,}$/).test(val)) {
                callback(new Error("请输入6位以上由数字、字母组合密码"));
              } else {
                callback();
              }
            },
            trigger: "blur"
          }
        ],
        cpwd: [
          {
            required: true,
            message: "请确认密码",
            trigger: "blur"
          },
          {
            validator: (rule, val, callback) => {
              if (val === "") {
                callback(new Error("请再次输入密码"));
              } else if (val !== this.account.upwd) {
                callback(new Error("两次输入密码不一致"));
              } else {
                callback();
              }
            },
            trigger: "blur"
          }
        ]
      }
    };
  },
  methods: {
    sendMsg: function() {
      const self = this;
      // if (self.timerid) return;
      let namePass;
      let emailPass;
      this.$refs["account"].validateField("uname", valid => {
        namePass = valid;
      });
      self.statusMsg = "";
      if (namePass) {
        return false;
      }
      this.$refs["account"].validateField("email", valid => {
        emailPass = valid;
      });
      if (!namePass && !emailPass) {
        self.$axios
          .post("/user/verify", {
            uname: encodeURIComponent(self.account.uname),
            email: self.account.email
          })
          .then(({ status, data }) => {
            if (status === 200 && data && data.code === "01") {
              let count = 60;
              self.statusMsg = `验证码已发送,剩余${count--}秒`;
              clearInterval(self.timerid);
              self.timerid = setInterval(function() {
                self.statusMsg = `验证码已发送,剩余${count--}秒`;
                if (count === 0) {
                  self.statusMsg = "";
                  clearInterval(self.timerid);
                }
              }, 1000);
            } else {
              self.statusMsg = data.msg;
              self.$message.error(data.msg);
            }
          });
      }
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    },
    register: function() {
      let self = this;
      this.$refs["account"].validate(valid => {
        if (valid) {
          self.$axios
            .post("/user/register", {
              uname: window.encodeURIComponent(self.account.uname),
              upwd: CryptoJS.MD5(self.account.upwd).toString(),
              email: self.account.email,
              code: self.account.code
            })
            .then(({ status, data }) => {
              if (status === 200) {
                if (data && data.code === "01") {
                  self.$message.success(data.msg);
                  self.$router.push("/login");
                } else {
                  self.error = data.msg;
                  self.$message.error(data.msg);
                }
              } else {
                self.error = `服务器出错，错误码:${status}`;
              }
              setTimeout(function() {
                self.error = "";
              }, 1500);
            });
        }
      });
    }
  }
};
</script>
<style lang="scss">
@import "~assets/css/public/account.scss";
</style>
